# Generated by Django 4.2 on 2023-04-20 13:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('treeMenuApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, help_text='Url used in your urls.py file to navigate to the menu page', max_length=255, verbose_name='Named URL'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.SlugField(help_text='Use it in templatetag for draw a menu', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='treeMenuApp.menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='Url used in your urls.py file to navigate to the menu item page', max_length=255, verbose_name='Named URL'),
        ),
    ]
