# Generated by Django 4.2 on 2023-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeMenuApp', '0002_menu_title_menu_url_alter_menu_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
