# Generated by Django 4.2 on 2023-04-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeMenuApp', '0003_menuitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_expanded',
            field=models.BooleanField(default=False),
        ),
    ]
